/* GFG Submission    (Minimum Multiplications to Reach End) */

/* Problem Statement: Given start, end and an array arr of n numbers. At each step, start is multiplied with any number in the array and then mod operation with 100000 is done to get the new start.

Your task is to find the minimum steps in which end can be achieved starting from start. If it is not possible to reach end, then return -1. */



/* Solution: Using Dijkstra's Algorithm with Queue 

The steps are increasing by +1 so queue will store everything in increasing order, so we can use queue instead of priority queue. */


// Time Complexity : O(100000 * N)
/* Where ‘100000’ are the total possible numbers generated by multiplication (hypothetical) and N = size of the array with numbers of which each node could be multiplied. */

// Space Complexity : O(100000 * N)                 // queue
/* Where ‘100000’ are the total possible numbers generated by multiplication (hypothetical) and N = size of the array with numbers of which each node could be multiplied. 100000 * N is the max possible queue size. The space complexity of the dist array is constant. */


// class Solution {
//   public:
//     int minimumMultiplications(vector<int>& arr, int start, int end) {
//         if(start == end){
//             return 0;
//         }
        
//         queue<pair<int, int>> q;    // {steps, num}
//         q.push({0, start});
        
//         // We can have numbers from 0 to 99999 (100000 numbers) after mod operation, so we can create a distance array of size 100000 to store the minimum steps required to reach each number. Any num after 100000 when modulo with 10^5 will give a number between 0 and 99999.
//         vector<int> dist(100000, INT_MAX);
//         dist[start] = 0;
        
//         while(!q.empty()){
//             auto [steps, node] = q.front();
//             q.pop();
            
//             for(auto it : arr){
//                 int num = (node * it) % 100000;
                
//                 // If the no. of multiplications are less than before in order to reach a number, we update the dist array.
//                 if(steps + 1 < dist[num]){
//                     dist[num] = steps + 1;
                    
//                     // Whenever we reach the end number return the calculated steps
//                     if(num == end){
//                         return dist[num];
//                     }
                    
//                     q.push({dist[num], num});
//                 }
//             }
//         }
        
//         return -1;
//     }
// };
